package controller;
import model.*;
import java.util.ArrayList;

/**
 * Write a description of class FriendController here.
 *
 * @author (your name)
 * @version (a version number or a date)
 */
public class LoanController {
    private FriendController FriendController;
    private LpController lpController;
    private Friend currentFriend = null;
    private Copy currentCopy = null;

    public LoanController(){
        FriendController = new FriendController();
        lpController = new LpController();

    }

    public Friend addFriendToLoan(String name){
        currentFriend = FriendController.findFriend(name);
        return currentFriend;

    }
    
    public Copy addCopyToLoan(int serialNumber){
        currentCopy = lpController.findCopy(serialNumber);
        return currentCopy;
    }


    public void addLoan(){
        Loan newLoan = new Loan(currentCopy, currentFriend);
        newLoan.AutoGenerateData();
        LoanContainer.getInstance().addLoan(newLoan);

    }

    public String getReturnedDate(String loanNumber){
        if(LoanContainer.getInstance().findReturnedDate(loanNumber) != null){

        }
        return LoanContainer.getInstance().findReturnedDate(loanNumber);
    }

    public void returned(String loanNumber, String date){
        LoanContainer.getInstance().findLoanNumber(loanNumber, date);

    }
}
